name: seemur_v1
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  loading:  
  firebase_auth: 
  flutter_auth_buttons:  
  flutter_facebook_login: 
  carousel_pro: 
  cloud_firestore: 
  flutter_svg: 
  cupertino_icons: ^0.1.2
  rect_getter: ^0.0.1  
  shared_preferences: 
  path_provider: 
  intro_slider: 
  modal_progress_hud: 
  intl: 
  datetime_picker_formfield: 
  firebase_storage_image: 
  date_format: 
  image_picker: 
  firebase_storage: 
  flutter_web_view: 
  url_launcher: 
  font_awesome_flutter: 
  localstorage: 
  flutter_webview_plugin:
  flutter_responsive_screen: ^1.0.0
  




dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  
  fonts:
     - family: CupertinoIcons
       fonts:
         - asset: assets/CupertinoIcons.ttf
     - family: HankenGrotesk
       fonts:
         - asset: fonts/HankenGrotesk-Regular.ttf
         - asset: fonts/HankenGrotesk-Bold.ttf
           #weight: 700
         - asset: fonts/HankenGrotesk-Light.ttf
           #weight: 300
           #style: italic
         - asset: fonts/HankenGrotesk-Black.ttf
         - asset: fonts/HankenGrotesk-ExtraLight.ttf
         - asset: fonts/HankenGrotesk-Medium.ttf
         - asset: fonts/HankenGrotesk-SemiBold.ttf
     - family: OpenSans
       fonts:
         - asset: fonts/OpenSans-Bold.ttf
         - asset: fonts/OpenSans-BoldItalic.ttf
         - asset: fonts/OpenSans-ExtraBold.ttf
         - asset: fonts/OpenSans-ExtraBoldItalic.ttf
         - asset: fonts/OpenSans-Italic.ttf
         - asset: fonts/OpenSans-Light.ttf
         - asset: fonts/OpenSans-LightItalic.ttf
         - asset: fonts/OpenSans-Regular.ttf
         - asset: fonts/OpenSans-SemiBold.ttf
         - asset: fonts/OpenSans-SemiBoldItalic.ttf
         


  uses-material-design: true


  assets:
     - assets/images/
     - assets/images/1.jpg
     - assets/images/2.jpg
     - assets/images/3.jpg
     - assets/images/4.jpeg
     - assets/seemurIsotipo.png
     - assets/logoSombrero.png
     - assets/logoblanco.png
