name: seemur_v1
description: A new Flutter project.


version: 1.0.5+6

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  loading: ^1.0.2
  firebase_auth: ^0.15.3
  firebase_core: ^0.4.3+1
  firebase_analytics: ^5.0.9
  flutter_auth_buttons: ^0.6.0
  carousel_pro: ^1.0.0
  cloud_firestore: ^0.13.0+1
  flutter_svg: ^0.15.0
  cupertino_icons: ^0.1.3
  rect_getter: ^0.0.1
  shared_preferences: ^0.5.6
  path_provider: ^1.5.1
  intro_slider: ^2.2.8
  modal_progress_hud: ^0.1.3
  intl: ^0.16.0
  datetime_picker_formfield: ^1.0.0-pre.5
  firebase_storage_image: ^0.4.0
  date_format: ^1.0.8
  image_picker: ^0.6.2+3
  firebase_storage: ^3.1.0
  flutter_web_view: ^0.0.6
  url_launcher: ^5.4.1
  font_awesome_flutter: ^8.5.0
  flutter_webview_plugin: ^0.3.10
  flutter_responsive_screen: ^1.0.0
  flutter_launcher_icons: ^0.7.4
  flutter_range_slider: ^1.4.0
  smooth_star_rating: ^1.0.3
  flutter_share_me: ^0.8.0
  provider: ^3.2.0
  cached_network_image: ^2.0.0-rc.1
  flutter_image_compress: ^0.6.3
  uuid: ^2.0.4







dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"




flutter:
  fonts:
     - family: CupertinoIcons
       fonts:
         - asset: assets/CupertinoIcons.ttf
     - family: HankenGrotesk
       fonts:
         - asset: fonts/HankenGrotesk-Regular.ttf
         - asset: fonts/HankenGrotesk-Bold.ttf
           #weight: 700
         - asset: fonts/HankenGrotesk-Light.ttf
           #weight: 300
           #style: italic
         - asset: fonts/HankenGrotesk-Black.ttf
         - asset: fonts/HankenGrotesk-ExtraLight.ttf
         - asset: fonts/HankenGrotesk-Medium.ttf
         - asset: fonts/HankenGrotesk-SemiBold.ttf
     - family: OpenSans
       fonts:
         - asset: fonts/OpenSans-Bold.ttf
         - asset: fonts/OpenSans-BoldItalic.ttf
         - asset: fonts/OpenSans-ExtraBold.ttf
         - asset: fonts/OpenSans-ExtraBoldItalic.ttf
         - asset: fonts/OpenSans-Italic.ttf
         - asset: fonts/OpenSans-Light.ttf
         - asset: fonts/OpenSans-LightItalic.ttf
         - asset: fonts/OpenSans-Regular.ttf
         - asset: fonts/OpenSans-SemiBold.ttf
         - asset: fonts/OpenSans-SemiBoldItalic.ttf
  uses-material-design: true
  assets:
        - assets/images/
        - assets/seemurIsotipo.png
        - assets/logoSombrero.png
        - assets/logoblanco.png
        - assets/icon/icon.png
        - assets/images/seemurapp.gif
        - assets/images/seemurapp2.gif
        - assets/images/seemurapp3.gif
        

      